services:
  usersService:
    image: eclipse-temurin:21-jdk-jammy
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./usersService/target:/app:ro
    env_file:
      - ./usersService/.env
    environment:
      - JAVA_OPTS=-Xmx512m
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
      - MICRONAUT_SERVER_PORT=8080
    command: ["java", "-jar", "/app/usersService-0.1.jar"]
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  microsservico-b:
    image: eclipse-temurin:21-jdk-jammy
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - ./microsservico-b/target:/app:ro
    env_file:
      - ./microsservico-b/.env
    environment:
      - JAVA_OPTS=-Xmx512m
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
      - MICRONAUT_SERVER_PORT=8081
    command: ["java", "-jar", "/app/microsservico-b-0.1.jar"]
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    image: eclipse-temurin:21-jdk-jammy
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./gateway/target:/app:ro
    environment:
      - JAVA_OPTS=-Xmx512m
      - MICRONAUT_SERVER_PORT=8000
      - PROXY_TARGETS_USERSSERVICE=http://usersService:8080
      - PROXY_TARGETS_MICROSSERVICOB=http://microsservico-b:8081
    command: ["java", "-jar", "/app/gateway-0.1.jar"]
    networks:
      - app-network
    depends_on:
      - usersService
      - microsservico-b

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=aluguel-carro
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d aluguel-carro"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8090:8081"
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/aluguel-carro?sslmode=disable
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge