# URLs dos microsserviços no ambiente local via Docker Compose
proxy:
  targets:
    usersservice: "http://usersService:8080"
    vehiclesservice: "http://vehiclesService:8081"
    rentalsservice: "http://rentalsService:8082"
    contratoservice: "http://contratoService:8083"
    reservasservice: "http://reservasService:8084"
