micronaut.security.token.jwt.signatures.secret.generator.secret=${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
micronaut.application.name=rentalsService
datasources.default.url=${DB_URL}
datasources.default.username=${DB_USER}
datasources.default.password=${DB_PASSWORD}
datasources.default.schema-generate=NONE
flyway.datasources.default.enabled=true
flyway.datasources.default.table=flyway_schema_history_rentals
flyway.datasources.default.baseline-on-migrate=true
flyway.datasources.default.baseline-version=0
micronaut.security.authentication=bearer
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.maximumPoolSize=3
datasources.default.minimumIdle=1
datasources.default.connectionTimeout=30000
datasources.default.maxLifetime=1800000
datasources.default.idleTimeout=600000
micronaut.security.enabled=true
micronaut.server.port=${MICRONAUT_SERVER_PORT:8082}
micronaut.security.intercept-url-map[0].pattern=/
micronaut.security.intercept-url-map[0].http-method=GET
micronaut.security.intercept-url-map[0].access=isAnonymous()
micronaut.security.intercept-url-map[1].pattern=/ping
micronaut.security.intercept-url-map[1].http-method=GET
micronaut.security.intercept-url-map[1].access=isAnonymous()

vehicles.service.url=${VEHICLES_SERVICE_URL:http://vehiclesService:8081}
users.service.url=${USERS_SERVICE_URL:http://usersService:8080}
